add crypto_box_seed_keypair
lyubo/react-native-sodium pull request #37
Opened 2020-07-17 01:38 UTC by DiogoAbu

This will add `crypto_box_seed_keypair` that allows to derive a key pair from a seed key.
Fix typo on types;
Add new type relative to the function added.

2020-07-21 07:36 UTC, lyubo commented
Hey @DiogoAbu , thanks for this PR. 
What's the reason of removing the checks like this one?

```
      if (Sodium.crypto_secretbox_keygen(key) != 0)
        p.reject(ESODIUM,ERR_FAILURE);
```

2020-07-21 15:00 UTC, DiogoAbu commented
Hello!
I didn't remove it though... was it ever there? I mean i wrote the `crypto_secretbox_keygen` method, and I can't find the check anywhere on the file history.
Should I add it?

2020-07-21 19:39 UTC, DiogoAbu commented on android/src/main/java/org/libsodium/rn/RCTSodiumModule.java
> -      if (Sodium.crypto_secretbox_keygen(key) != 0)
This code is part of the other pull request I made.

2020-09-24 12:17 UTC, lyubo requested changes
Please, split crypto_box_seed_keypair and crypto_pwhash* to separate PRs. Also, do not commit white-space changes to code which are not relevant to new functionality.

2020-10-26 07:48 UTC, lyubo commented
Closing this one because of conflicts with master branch. Please submit a new one.

2020-10-26 07:48 UTC, closed without merging