Feature/scalarmult
lyubo/react-native-sodium pull request #40
Opened 2020-09-14 15:57 UTC by IamFlowZ

2020-09-14 15:57 UTC, IamFlowZ commented
#38

2020-09-24 11:55 UTC, lyubo commented on android/src/main/java/org/libsodium/rn/RCTSodiumModule.java
> +    catch (Throwable t) {
Please, revert this change as it is not relevant to new functionality

2020-09-24 12:01 UTC, lyubo commented on android/src/main/java/org/libsodium/rn/RCTSodiumModule.java
> +  public void crypto_scalarmult(final String n, final String q, final Promise p) {
In native crypto_scalarmult n and p are the input parameters, while q is the output. Please correct parameter names of this method to reflect their purpose as in the original.

2020-09-24 12:05 UTC, lyubo commented on index.d.ts
> +    publicKey: string,
In relation to previous comment, I think the first argument should be 'n', which contains the private key (as in the libsodium documentation, see https://doc.libsodium.org/advanced/scalar_multiplication), and the second one is 'q'.

2020-09-24 12:07 UTC, lyubo commented on ios/RCTSodium/RCTSodium.m
> +RCT_EXPORT_METHOD(crypto_scalarmult:(NSString*)n p:(NSString*)p resolve:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject)
Parameter names as in my comments on java interface.

2020-09-24 12:09 UTC, lyubo requested changes
Please see my comments on files.

2020-09-30 06:31 UTC, merged